### ISSUE TITLE
Implement Ace for editing

### ISSUE THREAD

**Issue by dannytech** [AluminiumCode/AluminiumCode#1]
I've had quite a bit of experience with Node, and given one of your requirements is Syntax Highlighting, I thought I might suggest using [Ace](https://ace.c9.io/#nav=about), which supports (at the moment) over 110 languages for syntax highlighting and is completely open-source, so we can make any modifications necessary. I'd be happy to implement Ace for you if this is of interest.

**Comment by AluminiumTech** [comment]
I might have a look at the source code used in Ace and try to add certain things from it into the current editor.

Thanks for pointing this out 👍 .
